# OpenAI (brug miljøvariabel ? ingen nøgle i repo)
app.api-key=${APP_API_KEY}
app.url=https://api.openai.com/v1/chat/completions
app.model=gpt-4o-mini
app.temperature=0.0
app.max_tokens=400
app.top_p=1.0
app.frequency_penalty=0.0
app.presence_penalty=0.0

# Server
server.port=8080

# Static
spring.web.resources.add-mappings=true
