# OpenAI
app.api-key=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
app.url=https://api.openai.com/v1/chat/completions
app.model=gpt-4o-mini
app.temperature=0.0
app.max_tokens=400
app.top_p=1.0
app.frequency_penalty=0.0
app.presence_penalty=0.0

# Server (valgfrit)
server.port=8080

# Static (du bruger resources/static + resources/index.html already)
spring.web.resources.add-mappings=true
